### index.php as json:
GET http://localhost:80/newapi
Accept: application/json

### json.php with parameter g:
GET http://localhost:80/newapi/json?g=1
Accept: application/json

### xml-all.php as xml:
GET http://localhost:80/newapi/xml-all
Accept: application/xml

### xml.php with parameter g:
GET http://localhost:80/newapi/xml?g=1
Accept: application/xml

### param.php with parameter POSTed in json
POST http://localhost:80/newapi/param
Content-Type: application/json
Accept: application/json

{
  "group" : 1
}

### login.php with POST parameters:
POST http://localhost:80/newapi/login
Content-Type: application/x-www-form-urlencoded
Accept: application/json

login=Иван&password=12345

###